name: Update Kazumi Repo JSON from Kazumi Releases

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Feather-Repo
        uses: actions/checkout@v4

      - name: Fetch Kazumi releases
        run: |
          curl -s https://api.github.com/repos/Predidit/Kazumi/releases > releases.json

      - name: Generate Kazumi Repo.json
        run: |
          python3 <<EOF
          import json, os, datetime
          with open("releases.json") as f:
              releases = json.load(f)
          versions = []
          for release in releases:
              ipa = next((a for a in release["assets"] if a["name"].endswith(".ipa")), None)
              if not ipa: continue
              versions.append({
                  "version": release["tag_name"].lstrip("v"),
                  "date": release["published_at"].split("T")[0],
                  "localizedDescription": release["body"] or "",
                  "downloadURL": ipa["browser_download_url"],
                  "size": ipa["size"],
                  "minOSVersion": "15.0"
              })
          latest = versions[0] if versions else {}
          output = {
              "name": "Kazumi Compiled",
              "subtitle": "Compiled Tweaked Kazumi IPA's",
              "identifier": "com.predidit.Kazumi",
              "sourceURL": "https://raw.githubusercontent.com/DeAthBo/Feather-Repo/main/Kazumi%20Repo.json",
              "website": "https://github.com/Predidit/Kazumi",
              "iconURL": "https://raw.githubusercontent.com/Predidit/Kazumi/main/icon.png",
              "headerURL": "https://raw.githubusercontent.com/Predidit/Kazumi/main/header.png",
              "META": {
                  "repoName": "Kazumi Compiled",
                  "repoIcon": "https://raw.githubusercontent.com/Predidit/Kazumi/main/icon.png"
              },
              "apps": [
                  {
                      "name": "Kazumi",
                      "bundleIdentifier": "com.predidit.Kazumi",
                      "developerName": "Predidit",
                      "contact": {"web": "https://github.com/Predidit"},
                      "version": latest.get("version", ""),
                      "versionDate": latest.get("date", ""),
                      "size": latest.get("size", 0),
                      "minOSVersion": "15.0",
                      "changelog": latest.get("localizedDescription", ""),
                      "versionDescription": latest.get("localizedDescription", ""),
                      "information": [
                          {
                              "item": "Kazumi Core",
                              "version": latest.get("version", ""),
                              "authors": "Predidit",
                              "url": "https://github.com/Predidit/Kazumi"
                          }
                      ],
                      "subtitle": "Kazumi 强力侧载功能",
                      "versions": versions,
                      "downloadURL": latest.get("downloadURL", ""),
                      "localizedDescription": "Kazumi 是一款多功能侧载 iOS 应用。",
                      "iconURL": "https://raw.githubusercontent.com/Predidit/Kazumi/main/icon.png",
                      "tintColor": "1ed760",
                      "appPermissions": {
                          "entitlements": [],
                          "privacy": {}
                      },
                      "screenshotURLs": [],
                      "beta": False
                  }
              ]
          }
          with open("Kazumi Repo.json", "w") as out:
              json.dump(output, out, ensure_ascii=False, indent=2)
          EOF

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update Kazumi Repo.json from latest Kazumi releases"
